// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417035619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 885, DateTimeKind.Utc).AddTicks(2031),
                            PasswordHash = "$2a$11$ww6BxxZbpUtwDS8r9pdI5OSyud08jUB26HL1TvPaXp3cSgWdUVxVm",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 18, 83, DateTimeKind.Utc).AddTicks(6066),
                            PasswordHash = "$2a$11$o3hynhG9XurO/yYvSIg6NOzk11wsQmw6vRy7PVWy1gQeUEInHkxpK",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1266),
                            Department = "Engineering",
                            Designation = "Senior Developer",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            JoinDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            Phone = "9876543210",
                            Salary = 95000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1347)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1372),
                            Department = "Marketing",
                            Designation = "Marketing Manager",
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            JoinDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            Phone = "9876543211",
                            Salary = 75000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1373)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1390),
                            Department = "HR",
                            Designation = "HR Specialist",
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            JoinDate = new DateTime(2019, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            Phone = "9876543212",
                            Salary = 65000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1391)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1399),
                            Department = "Finance",
                            Designation = "Finance Analyst",
                            Email = "sarah.williams@example.com",
                            FirstName = "Sarah",
                            JoinDate = new DateTime(2021, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            Phone = "9876543213",
                            Salary = 70000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1401)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1409),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            JoinDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            Phone = "9876543214",
                            Salary = 80000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1410)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1425),
                            Department = "Engineering",
                            Designation = "Software Developer",
                            Email = "emily.davis@example.com",
                            FirstName = "Emily",
                            JoinDate = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            Phone = "9876543215",
                            Salary = 85000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1426)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1433),
                            Department = "Marketing",
                            Designation = "Content Specialist",
                            Email = "robert.miller@example.com",
                            FirstName = "Robert",
                            JoinDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Miller",
                            Phone = "9876543216",
                            Salary = 60000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1435)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1442),
                            Department = "HR",
                            Designation = "Recruiter",
                            Email = "jessica.taylor@example.com",
                            FirstName = "Jessica",
                            JoinDate = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            Phone = "9876543217",
                            Salary = 55000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1443)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1451),
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "christopher.anderson@example.com",
                            FirstName = "Christopher",
                            JoinDate = new DateTime(2020, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Anderson",
                            Phone = "9876543218",
                            Salary = 62000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1452)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1463),
                            Department = "Operations",
                            Designation = "Operations Specialist",
                            Email = "jennifer.thomas@example.com",
                            FirstName = "Jennifer",
                            JoinDate = new DateTime(2021, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thomas",
                            Phone = "9876543219",
                            Salary = 58000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1465)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1473),
                            Department = "Engineering",
                            Designation = "DevOps Engineer",
                            Email = "daniel.jackson@example.com",
                            FirstName = "Daniel",
                            JoinDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Jackson",
                            Phone = "9876543220",
                            Salary = 92000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1474)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1482),
                            Department = "Marketing",
                            Designation = "Social Media Manager",
                            Email = "lisa.white@example.com",
                            FirstName = "Lisa",
                            JoinDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "White",
                            Phone = "9876543221",
                            Salary = 52000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1484)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1511),
                            Department = "Finance",
                            Designation = "Senior Accountant",
                            Email = "mark.harris@example.com",
                            FirstName = "Mark",
                            JoinDate = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Harris",
                            Phone = "9876543222",
                            Salary = 78000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1513)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1521),
                            Department = "HR",
                            Designation = "HR Manager",
                            Email = "amanda.martin@example.com",
                            FirstName = "Amanda",
                            JoinDate = new DateTime(2018, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martin",
                            Phone = "9876543223",
                            Salary = 72000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1523)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1531),
                            Department = "Operations",
                            Designation = "Quality Assurance",
                            Email = "steven.thompson@example.com",
                            FirstName = "Steven",
                            JoinDate = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Thompson",
                            Phone = "9876543224",
                            Salary = 64000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 4, 17, 3, 56, 17, 616, DateTimeKind.Utc).AddTicks(1533)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
